import type { Metadata } from "next";
import "@/styles/globals.css";
import { onest } from '@/styles/fonts'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className='text-text bg-background transition-colors'>
      <body className={onest.className}>
        {children}
      </body>
    </html>
  );
}
